// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1FwaUXmZ4aeF86j2uvRRc6GapO1UauA',
    appId: '1:501788244743:web:67eef242475ac0c8fb63a2',
    messagingSenderId: '501788244743',
    projectId: 'test-app-3e7d1',
    authDomain: 'test-app-3e7d1.firebaseapp.com',
    storageBucket: 'test-app-3e7d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgi6qdFZ7p3HiHm7c-QGrYyktb_fynKVw',
    appId: '1:501788244743:android:a089fcb124e8209efb63a2',
    messagingSenderId: '501788244743',
    projectId: 'test-app-3e7d1',
    storageBucket: 'test-app-3e7d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOjOeATVDWGmJFDHiml4mSFdyYt--SlU',
    appId: '1:501788244743:ios:0c8ddde3d6a50171fb63a2',
    messagingSenderId: '501788244743',
    projectId: 'test-app-3e7d1',
    storageBucket: 'test-app-3e7d1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOjOeATVDWGmJFDHiml4mSFdyYt--SlU',
    appId: '1:501788244743:ios:e149739104616c0bfb63a2',
    messagingSenderId: '501788244743',
    projectId: 'test-app-3e7d1',
    storageBucket: 'test-app-3e7d1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
